### ISSUE TITLE
Plugin broken by changes in TestRail v7.2.1.3027

### ISSUE THREAD

**Issue by JohnOSu** [vietnq254/pytest-testrail-e2e#3]
The changes described here have now been implemented:
https://discuss.gurock.com/t/bulk-api-endpoint-changes-coming-soon/19537

These calls now need to be able to handle the paginated responses:
get_cases
get_runs
get_results
get_tests
get_results_for_case
get_results_for_run
get_plans
get_projects
get_sections
get_milestones
get_history_for_case
get_attachments_for_case
get_attachments_for_run
Get_attachments_for_plan

**Comment by JohnOSu** [comment]
In case it helps anybody, this workaround works for me:

`

    def get_tests(self, run_id):
        """
        :return: the list of tests containing in a testrun.

        """
        from urllib.parse import parse_qsl, urlencode

        master_test_list = []
        repeat = True
        params = None

        while repeat:
            uri = GET_TESTS_URL.format(run_id)
            if params:
                uri = uri+params
            response = self.client.send_get(uri, cert_check=self.cert_check)

            error = self.client.get_error(response)
            if error:
                print('[{}] Failed to get tests: "{}"'.format(TESTRAIL_PREFIX, error))
                return None

            test_list = [item for item in response['tests']]
            master_test_list.extend(test_list)

            repeat = response['_links']['next']
            if repeat:
                params = f'&{urlencode(parse_qsl(repeat))}'

        return master_test_list

`

**Comment by vietnq254** [comment]
Thanks @JohnOSu for reporting the issue.

I released new version to include the fix.
